sudo: required
services:
  - docker
language: bash
env:
  - IMAGE_NAME=dnsmasq
  - IMAGE_NAME=frpc
  - IMAGE_NAME=frps
  # Split nginx build to speed up
  - IMAGE_NAME=nginx      IMAGE_ARCH=amd64
  - IMAGE_NAME=nginx      IMAGE_ARCH=arm32v7
  - IMAGE_NAME=nginx      IMAGE_ARCH=arm64v8
  - IMAGE_NAME=nyancat
  - IMAGE_NAME=php7-fpm
  - IMAGE_NAME=route-next
  - IMAGE_NAME=plus1s

install:
  - |
    docker run --rm --privileged multiarch/qemu-user-static:register --reset
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - |
    if [ $IMAGE_ARCH ]
    then
      # Determined IMAGE_ARCH
      cd $IMAGE_NAME
      travis_wait 60 docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_ARCH -f Dockerfile.$IMAGE_ARCH .
    else
      cd $IMAGE_NAME
      for IMAGE_ARCH in $(ls -1 Dockerfile.* | cut -d'.' -f2)
      do
        travis_wait 60 docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_ARCH -f Dockerfile.$IMAGE_ARCH .
      done
    fi

after_script:
  - |
    docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_ARCH
    if [ $IMAGE_ARCH = "amd64" ]; then
      docker tag $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_ARCH $DOCKER_USERNAME/$IMAGE_NAME:latest
      docker push $DOCKER_USERNAME/$IMAGE_NAME:latest
    fi